#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, counting occurrences and sorting by frequency

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
