#!/usr/bin/env bash
# Groups IP + HTTP status code and counts occurrences sorted descending

awk '
{
    key = $1 " " $9
    count[key]++
}
END {
    for (k in count) {
        print count[k], k
    }
}' apache-access.log | sort -nr
